version: "3.0"
services:
  rasa:
    image: rasa/rasa:3.0.4-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
  actions:
    image: rasa/myeats
    expose:
      - 5055
  duckling:
    image: rasa/duckling
    expose:
      - 8000
